included:
    - Sources

# rule identifiers to exclude from running
disabled_rules:
    - file_length
    - cyclomatic_complexity
    - identifier_name

shorthand_operator: warning

# some rules are only opt-in
opt_in_rules:
    - empty_count

# configurable rules can be customized from this configuration file
line_length:
- 230
- 250

function_body_length:
- 50
- 100
